# Generated by Django 5.0.3 on 2024-03-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_timestamp_post_timestamp_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogcomment',
        ),
    ]
