# Generated by Django 5.0.3 on 2024-03-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='order_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
