# Generated by Django 5.0.3 on 2024-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_coffee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
